trigger: none

pool: Default

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'aafbb9e4-97ea-4d84-981e-f33051962c90'
  imageRepository: 'Game-Server'
  #containerRegistry: 'repoistoryname.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Game.Server/Dockerfile'
  tag: '$(Build.BuildId)'


stages:
  - stage: Build
    jobs:
    - job: Build_Server
      steps:
      - task: CmdLine@2
        inputs:
          script: |
            echo "Structure of work folder of this pipeline:"
            tree $(Agent.WorkFolder)/1

            echo "Build.ArtifactStagingDirectory:" 
            echo "$(Build.ArtifactStagingDirectory)"

            echo "Build.BinariesDirectory:" 
            echo "$(Build.BinariesDirectory)"

            echo "Build.SourcesDirectory:"
            echo "$(Build.SourcesDirectory)"

      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: $(imageRepository)
          dockerfile: $(dockerfilePath)
          buildContext: $(Build.SourcesDirectory)
          containerRegistry: $(dockerRegistryServiceConnection)
          tags: |
            $(tag)