trigger: none

pool: Default

variables:
  tag: '$(Build.BuildNumber)'


stages:
  - stage: Build
    jobs:
    - job: Build_Server
      steps:
      - task: DockerInstaller@0
      - task: Docker@2
        displayName: Build Image
        inputs:
          command: build
          repository: 'Game-Server'
          dockerfile: '$(Build.SourcesDirectory)/Game.Server/Dockerfile'
          buildContext: $(Build.SourcesDirectory)
          tags: |
            $(tag)
      - task: CmdLine@2
        displayName: Prune Dangling Images
        inputs:
          script: |
            docker image prune -f

    - job: Build_Client
      steps:
      - task: CmdLine@2
        displayName: Hello World
        inputs:
          script: |
            echo "Hello World"

  - stage: Deploy
    jobs:
    - deployment: Deploy_Server
      displayName: Deploy Server
      environment: DEV
      strategy: 
        runOnce:
          deploy:
            steps:
              - task: CmdLine@2
                displayName: Hello World
                inputs:
                  script: |
                    echo "Hello World"
    - deployment: Deploy_Client
      displayName: Deploy Client
      environment: DEV
      strategy: 
        runOnce:
          deploy:
            steps:
              - task: CmdLine@2
                displayName: Hello World
                inputs:
                  script: |
                    echo "Hello World"