trigger: none

pool: Default

variables:
- group: 'DEV - Environment Variables'

jobs:
- deployment: Deploy_Server
  displayName: Deploy Server
  environment: DEV
  strategy: 
    runOnce:
      deploy:
        steps:
          # TODO: Generate Encryption Keys and inject as ENV variables? also need to figure out way for client. (streamingAssets)
          - checkout: self
          - task: CmdLine@2
            displayName: Deploy Server
            inputs:
              script: |
                tree
                docker compose -f '$(Build.SourcesDirectory)/Game.Server/docker-compose.yml' up -d 
            env:
              IMAGE_TAG: latest
              PlayFabOptions__TitleID: $(PlayFabOptions__TitleID)
              PlayFabOptions__DeveloperSecretKey: $(PlayFabOptions__DeveloperSecretKey)
- deployment: Deploy_Client
  displayName: Deploy Client
  environment: DEV
  strategy: 
    runOnce:
      deploy:
        steps:
          #NEED TO DOWNLOAD ARTIFACT
          - download: current
            patterns: '**/*.zip'

          - task: CmdLine@2
            displayName: Login to minio
            inputs:
              script: |
                mc alias set miniodev $(minioUrl) $(minioAccessKey) $(minioSecretKey)
          - task: CmdLine@2
            displayName: Upload Artifact to minio
            inputs:
              script: |
                mc cp ARTIFACT "miniodev/shooter/releases/"