trigger: none

pool: Default

variables:
- group: 'DEV - Environment Variables'
- name: repository
  value: 'game-server'
- name: 'unityPath'
  value: '/opt/unity/editors/2022.3.4f1/Editor/Unity'

jobs:
- job: Build_Server
  steps:
  - task: Docker@2
    displayName: Build Image
    inputs:
      command: build
      repository: '$(repository)'
      dockerfile: '$(Build.SourcesDirectory)/Game.Server/Dockerfile'
      buildContext: $(Build.SourcesDirectory)
      tags: |
        latest
        $(Build.BuildNumber)
  - task: CmdLine@2
    displayName: Prune Dangling Images
    inputs:
      script: |
        docker image prune -f
- job: Build_Client
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build Game.Common
    inputs:
      command: 'build'
      projects: "**/Game.Common.csproj"
      arguments: '--configuration $(buildConfiguration)'
      displayName: 'dotnet build $(buildConfiguration)'
  - script: |
      tree 

  - task: DownloadSecureFile@1
    name: unityLicense
    displayName: "Download Unity License"
    inputs:
        secureFile: "Unity_v2022.x.ulf"
  - script: |
      cp "$(unityLicense.secureFilePath)" Unity_v2022.x.ulf
      tree 
    displayName: "Copy License File"
  - script: |
      $(unityPath) -quit -batchmode -nographics -accept-apiupdate -manualLicenseFile Unity_v2022.x.ulf  -username "$(unityUsername)" -password "$(unityPassword)"
  - script: |
      $(unityPath) -quit -batchmode -nographics -accept-apiupdate -buildTarget StandaloneWindows -executeMethod Builder.Build -projectPath $(Build.SourcesDirectory)/Game.Client/

  - task: CmdLine@2
    displayName: Hello World
    inputs:
      script: |
        echo "Hello World"