trigger: none

pool: Default

variables:
- group: 'DEV - Environment Variables'
- name: repository
  value: 'game-server'
- name: 'unityPath'
  value: '/opt/unity/editors/2022.3.4f1/Editor/Unity'

jobs:
- job: Build_Server
  steps:
  - task: Docker@2
    displayName: Build Image
    inputs:
      command: build
      repository: '$(repository)'
      dockerfile: '$(Build.SourcesDirectory)/Game.Server/Dockerfile'
      buildContext: $(Build.SourcesDirectory)
      tags: |
        latest
        $(Build.BuildNumber)
  - task: CmdLine@2
    displayName: Prune Dangling Images
    inputs:
      script: |
        docker image prune -f
- job: Build_Client
  steps:
  - task: DownloadSecureFile@1
    name: unityLicense
    displayName: "Download Unity License"
    inputs:
        secureFile: "Unity_lic.ulf"
  - script: |
      cp "$(unityLicense.secureFilePath)" Unity_lic.ulf
      tree 
    displayName: "Copy License File"
  - script: |
      $(unityPath) -quit -batchmode -nographics -accept-apiupdate -manualLicenseFile Unity_lic.ulf -buildTarget StandaloneWindows -executeMethod Builder.Build -projectPath $(Build.SourcesDirectory)/Game.Client/
  - script: |
      $(unityPath) -quit -batchmode -nographics -accept-apiupdate -username "$(unityUsername)" -password "$(unityPassword)"
  - script: |
      $(unityPath) -quit -batchmode -nographics -returnlicense -username $(unityUsername) -password $(unityPassword) 


  - task: CmdLine@2
    displayName: Hello World
    inputs:
      script: |
        echo "Hello World"