trigger: none

pool: Default

variables:
- group: 'DEV - Environment Variables'
- name: repository
  value: 'game-server'
- name: 'unityPath'
  value: '/opt/unity/Editor/Unity'

jobs:
- job: Build_Server
  steps:
  - task: Docker@2
    displayName: Build Image
    inputs:
      command: build
      repository: '$(repository)'
      dockerfile: '$(Build.SourcesDirectory)/Game.Server/Dockerfile'
      buildContext: $(Build.SourcesDirectory)
      tags: |
        latest
        $(Build.BuildNumber)
  - task: CmdLine@2
    displayName: Prune Dangling Images
    inputs:
      script: |
        docker image prune -f
- job: Build_Client
  steps:
  - script: |
      $(unityPath) -quit -batchmode -nographics -accept-apiupdate -username "$(unityUsername)" -password "$(unityPassword)" -projectPath "$(Build.SourcesDirectory)/Game.Client/"
  - script: |
      $(unityPath) -quit -batchmode -returnlicense -username $(unityUsername) -password $(unityPassword) 
  - script: |
      $(unityPath) -quit -batchmode -nographics -buildTarget StandaloneWindows -executeMethod Builder.Build -projectPath $(Build.SourcesDirectory)/Game.Client/

  - task: CmdLine@2
    displayName: Hello World
    inputs:
      script: |
        echo "Hello World"